# One Hot Encoder

In [18]:
import numpy as np
import pandas as pd

#### 1. Read dataset (data.csv)

In [2]:
data = pd.read_csv('data.csv')
data

luas  harga     kota
0   1000   1000    Depok
1   2000   2000    Depok
2   3000   3000    Depok
3   4000   4000    Depok
4   5000   5000    Depok
5   1000    500    Bogor
6   2000   1000    Bogor
7   3000   1500    Bogor
8   4000   2000    Bogor
9   5000   2500    Bogor
10  1000   2000  Jakarta
11  2000   4000  Jakarta
12  3000   6000  Jakarta
13  4000   8000  Jakarta
14  5000  10000  Jakarta

#### 2. Labelling - Sklearn Label Encoder

In [10]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
dataLabel = data
dataLabel['kota'] = label.fit_transform(dataLabel['kota'])
dataLabel
# label.classes_
# label.inverse_transform([0,1,2])

luas  harga  kota
0   1000   1000     1
1   2000   2000     1
2   3000   3000     1
3   4000   4000     1
4   5000   5000     1
5   1000    500     0
6   2000   1000     0
7   3000   1500     0
8   4000   2000     0
9   5000   2500     0
10  1000   2000     2
11  2000   4000     2
12  3000   6000     2
13  4000   8000     2
14  5000  10000     2

In [33]:
x = dataLabel[[ 'luas' , 'kota' ]].values
y = dataLabel['harga']
x

array([[1000,    1],
       [2000,    1],
       [3000,    1],
       [4000,    1],
       [5000,    1],
       [1000,    0],
       [2000,    0],
       [3000,    0],
       [4000,    0],
       [5000,    0],
       [1000,    2],
       [2000,    2],
       [3000,    2],
       [4000,    2],
       [5000,    2]], dtype=int64)

#### 3. One Hot Encoder

In [34]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# col trans
coltrans = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],
    remainder = 'passthrough'
)
# coltrans.fit_transform(x)
x = np.array(coltrans.fit_transform(x), dtype = np.int64)
x

array([[   0,    1,    0, 1000],
       [   0,    1,    0, 2000],
       [   0,    1,    0, 3000],
       [   0,    1,    0, 4000],
       [   0,    1,    0, 5000],
       [   1,    0,    0, 1000],
       [   1,    0,    0, 2000],
       [   1,    0,    0, 3000],
       [   1,    0,    0, 4000],
       [   1,    0,    0, 5000],
       [   0,    0,    1, 1000],
       [   0,    0,    1, 2000],
       [   0,    0,    1, 3000],
       [   0,    0,    1, 4000],
       [   0,    0,    1, 5000]], dtype=int64)

#### 4. linear regression

In [36]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x, y)
model.predict([[ 0, 1, 0, 1000]])

array([666.66666667])

In [37]:
model.predict([[ 1, 0, 0, 1000]])

array([-833.33333333])

In [38]:
model.predict([[ 0, 0, 1, 1000]])

array([3666.66666667])